version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  postgres-data:
  minio:
  rabbitmq:


services:
  backend:
    container_name: backend
    build:
        context: .
        dockerfile: Dockerfile
    hostname: backend
    ports:
      - 8000:8000
    env_file: .env.dev
    restart: always
    depends_on:
      - redis
    networks:
      - net

  redis:
    image: redis
    container_name: redis
    hostname: redis
    networks:
      - net